version: 2
updates:
  - package-ecosystem: composer
    directory: /legacy
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
